# Generated by Django 3.2.4 on 2021-06-30 14:18

from django.db import migrations, models
import reg_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=reg_profile.models.code_generator, max_length=5)),
                ('activated', models.BooleanField(default=False)),
                ('action', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
